# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-esql-js
  description: Buildkite Pipeline for esql-js
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/esql-js

spec:
  type: buildkite-pipeline
  owner: group:kibana-esql
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: esql-js
      description: A set of tools to parse, build and transform ES|QL queries programatically.
    spec:
      repository: elastic/esql-js
      pipeline_file: '.buildkite/pipeline.yml'
      provider_settings:
        build_pull_request_forks: true
      teams:
        kibana-esql:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-esql-js-release
  description: Release pipeline for esql-js
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/esql-js-release

spec:
  type: buildkite-pipeline
  owner: group:kibana-esql
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: esql-js-release
      description: Release pipeline for esql-js
    spec:
      repository: elastic/esql-js
      pipeline_file: '.buildkite/release-pipeline.yml'
      branch_configuration: '*'
      provider_settings:
        trigger_mode: none
      teams:
        kibana-esql:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
