---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: 'Quick checks'
    command: 'yarn lint && yarn format:check'

  - label: 'Build'
    command: 'yarn build'

  - label: 'Test'
    command: 'yarn test'
