---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
definitions:
  agents: &agents
    provider: 'gcp'
    image: 'family/kibana-ubuntu-2404'
    imageProject: 'elastic-images-prod'
    machineType: 'c2-standard-4'

steps:
  - label: 'Lint, Format & Build'
    key: 'check-and-build'
    agents: *agents
    command: |
      .buildkite/scripts/setup_pnpm.sh
      pnpm install --frozen-lockfile
      pnpm lint
      pnpm format:check
      pnpm build
      pnpm typecheck
      pnpm test
