---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
definitions:
  agents: &agents
    provider: 'gcp'
    image: 'family/kibana-ubuntu-2404'
    imageProject: 'elastic-images-prod'
    machineType: 'n2-standard-2'

steps:
  # TODO: remove after verifying grammar sync works (run on this PR then merge)
  - label: 'Grammar Sync'
    command: '.buildkite/scripts/esql_grammar_sync.sh'
    timeout_in_minutes: 10
    agents: *agents

  - label: 'Lint, Format & Build'
    key: 'check-and-build'
    agents: *agents
    command: |
      yarn install --frozen-lockfile
      yarn lint
      yarn format:check
      yarn build

  - label: 'Test'
    agents: *agents
    depends_on: 'check-and-build'
    command: |
      yarn install --frozen-lockfile
      yarn test
