/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { basename, join } from 'node:path';

import type {
  CommandDefinition,
  DefinitionDocs,
  FunctionDefinition,
  InlineCastMap,
  OperatorDefinition,
  PromqlFunctionDefinition,
  PromqlOperatorDefinition,
  SettingDefinition,
} from '../src/definition_types';

const LICENSE_HEADER = `/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */`;

const GENERATED_NOTICE =
  '// DO NOT MODIFY THIS FILE BY HAND. IT IS GENERATED FROM `elasticsearch/` BY' +
  '\n// `yarn workspace @elastic/esql-definitions generate`.';

const sourcedNotice = (source: string): string =>
  '// DO NOT MODIFY THIS FILE BY HAND. IT IS GENERATED BY' +
  '\n// `yarn workspace @elastic/esql-definitions generate` FROM' +
  `\n// \`${source}\`.`;

type Json = Record<string, unknown>;

export interface GeneratedFile {
  /** Path relative to `src/generated/`. */
  relativePath: string;
  content: string;
}

export interface GenerateResult {
  files: GeneratedFile[];
  warnings: string[];
  data: {
    commands: CommandDefinition[];
    functions: FunctionDefinition[];
    functionDocs: Record<string, DefinitionDocs>;
    operators: OperatorDefinition[];
    operatorDocs: Record<string, DefinitionDocs>;
    settings: SettingDefinition[];
    inlineCasts: InlineCastMap;
    promqlFunctions: PromqlFunctionDefinition[];
    promqlFunctionDocs: Record<string, DefinitionDocs>;
    promqlOperators: PromqlOperatorDefinition[];
    promqlOperatorDocs: Record<string, DefinitionDocs>;
  };
}

interface KeySpec {
  src: string;
  /** Emitted key name; defaults to `src`. */
  dst?: string;
  required?: boolean;
  /** Sanitize the value (an object, or an array of objects) with this spec. */
  children?: ObjectSpec;
  childrenAreArray?: boolean;
}

interface ObjectSpec {
  keys: KeySpec[];
  /** Known keys that are intentionally not emitted. */
  drop: string[];
}

const HINT_SPEC: ObjectSpec = {
  keys: [
    { src: 'kind', required: true },
    { src: 'entityType' },
    { src: 'allowedValues' },
    { src: 'constraints' },
  ],
  drop: [],
};

const PARAM_SPEC: ObjectSpec = {
  keys: [
    { src: 'name', required: true },
    { src: 'type', required: true },
    { src: 'optional', required: true },
    { src: 'description' },
    { src: 'hint', children: HINT_SPEC },
    { src: 'mapParams' },
  ],
  drop: [],
};

const SIGNATURE_SPEC: ObjectSpec = {
  keys: [
    { src: 'params', required: true, children: PARAM_SPEC, childrenAreArray: true },
    { src: 'variadic', required: true },
    { src: 'returnType', required: true },
    { src: 'license' },
  ],
  drop: [],
};

const COMMAND_SPEC: ObjectSpec = {
  keys: [
    { src: 'name', required: true },
    { src: 'license' },
    { src: 'observability_tier', dst: 'observabilityTier' },
    { src: 'output' },
  ],
  drop: ['comment', 'type'],
};

const FUNCTION_SPEC: ObjectSpec = {
  keys: [
    { src: 'type', required: true },
    { src: 'name', required: true },
    { src: 'description', required: true },
    { src: 'signatures', required: true, children: SIGNATURE_SPEC, childrenAreArray: true },
    { src: 'examples', required: true },
    { src: 'preview', required: true },
    { src: 'snapshot_only', dst: 'snapshotOnly', required: true },
    { src: 'license' },
    { src: 'observability_tier', dst: 'observabilityTier' },
    { src: 'note' },
    { src: 'tsdb_compatible', dst: 'tsdbCompatible' },
  ],
  drop: ['comment'],
};

const OPERATOR_SPEC: ObjectSpec = {
  keys: [
    { src: 'operator', required: true },
    { src: 'name', required: true },
    { src: 'titleName' },
    { src: 'description', required: true },
    { src: 'signatures', required: true, children: SIGNATURE_SPEC, childrenAreArray: true },
    { src: 'examples' },
    { src: 'preview', required: true },
    { src: 'snapshot_only', dst: 'snapshotOnly', required: true },
    { src: 'note' },
  ],
  drop: ['comment', 'type'],
};

const SETTING_SPEC: ObjectSpec = {
  keys: [
    { src: 'name', required: true },
    { src: 'type', required: true },
    { src: 'description', required: true },
    { src: 'serverlessOnly', required: true },
    { src: 'preview', required: true },
    { src: 'snapshotOnly', required: true },
    { src: 'mapParams' },
  ],
  drop: ['comment'],
};

const PROMQL_FUNCTION_SPEC: ObjectSpec = {
  keys: [
    { src: 'type', required: true },
    { src: 'name', required: true },
    { src: 'description', required: true },
    { src: 'signatures', required: true, children: SIGNATURE_SPEC, childrenAreArray: true },
    { src: 'examples', required: true },
    { src: 'snapshot_only', dst: 'snapshotOnly', required: true },
  ],
  drop: ['comment'],
};

// Unlike ES|QL operators, `type` is meaningful here
// ('operator' vs 'label_matching_operator'), so it is kept.
const PROMQL_OPERATOR_SPEC: ObjectSpec = {
  keys: [
    { src: 'type', required: true },
    { src: 'operator', required: true },
    { src: 'name', required: true },
    { src: 'description', required: true },
    { src: 'signatures', required: true, children: SIGNATURE_SPEC, childrenAreArray: true },
    { src: 'examples', required: true },
    { src: 'snapshot_only', dst: 'snapshotOnly', required: true },
  ],
  drop: ['comment'],
};

function sanitize(raw: Json, spec: ObjectSpec, label: string, warnings: string[]): Json {
  const out: Json = {};

  for (const key of spec.keys) {
    if (!Object.prototype.hasOwnProperty.call(raw, key.src)) {
      if (key.required) {
        throw new Error(`${label}: missing required key "${key.src}"`);
      }
      continue;
    }

    let value = raw[key.src];

    if (key.children) {
      const children = key.children;
      value = key.childrenAreArray
        ? (value as Json[]).map((item, i) =>
            sanitize(item, children, `${label}.${key.src}[${i}]`, warnings)
          )
        : sanitize(value as Json, children, `${label}.${key.src}`, warnings);
    }

    out[key.dst ?? key.src] = value;
  }

  const knownKeys = new Set([...spec.keys.map((key) => key.src), ...spec.drop]);

  for (const key of Object.keys(raw)) {
    if (!knownKeys.has(key)) {
      warnings.push(
        `${label}: unknown key "${key}" ignored — update definition_types.ts and generate_lib.ts if it should be emitted`
      );
    }
  }

  return out;
}

/**
 * Lists the project directories (`x-pack-esql`, `x-pack-esql-function-math`,
 * ...) under a language root. The projects partition the definitions, so all
 * of them are traversed and merged.
 */
function listProjectDirs(languageDir: string): string[] {
  if (!existsSync(languageDir)) {
    return [];
  }

  return readdirSync(languageDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

interface SourcedItem {
  item: Json;
  /** Package-relative path of the source JSON, e.g. `elasticsearch/esql/x-pack-esql/definition/functions/abs.json`. */
  source: string;
}

function readDefinitions(
  languageDir: string,
  kind: string,
  spec: ObjectSpec,
  warnings: string[]
): SourcedItem[] {
  const language = basename(languageDir);
  const names = new Map<string, string>();
  const items: SourcedItem[] = [];

  for (const project of listProjectDirs(languageDir)) {
    const dir = join(languageDir, project, 'definition', kind);

    if (!existsSync(dir)) {
      continue;
    }

    const files = readdirSync(dir)
      .filter((file) => file.endsWith('.json'))
      .sort();

    for (const file of files) {
      const label = `elasticsearch/${language}/${project}/definition/${kind}/${file}`;
      let raw: Json;

      try {
        raw = JSON.parse(readFileSync(join(dir, file), 'utf8')) as Json;
      } catch (error) {
        throw new Error(`${label}: invalid JSON: ${String(error)}`, { cause: error });
      }

      const item = sanitize(raw, spec, label, warnings);
      const name = item.name as string;

      // Some operator files use spaces where the name uses underscores,
      // e.g. "not in.json" holds "not_in".
      if (name !== file.slice(0, -'.json'.length).replace(/ /g, '_')) {
        throw new Error(`${label}: name "${name}" does not match the file name`);
      }
      if (names.has(name)) {
        throw new Error(`${label}: duplicate name "${name}" (also in ${names.get(name)})`);
      }
      if (!/^[a-z][a-z0-9_]*$/.test(name) || name === 'index') {
        throw new Error(`${label}: name "${name}" is not usable as a generated module name`);
      }

      names.set(name, label);
      items.push({ item, source: label });
    }
  }

  return items.sort((a, b) => (a.item.name as string).localeCompare(b.item.name as string));
}

function readInlineCastMap(languageDir: string): InlineCastMap {
  const merged: InlineCastMap = {};
  const sources = new Map<string, string>();

  for (const project of listProjectDirs(languageDir)) {
    const path = join(languageDir, project, 'definition', 'inline_cast.json');

    if (!existsSync(path)) {
      continue;
    }

    const label = `${project}/definition/inline_cast.json`;
    const raw = JSON.parse(readFileSync(path, 'utf8')) as Json;

    for (const [key, value] of Object.entries(raw)) {
      if (typeof value !== 'string') {
        throw new Error(`${label}: value of "${key}" is not a string`);
      }
      if (key in merged && merged[key] !== value) {
        throw new Error(`${label}: conflicting value for "${key}" (also in ${sources.get(key)})`);
      }

      merged[key] = value;
      sources.set(key, label);
    }
  }

  return merged;
}

interface DocsSplit {
  structure: SourcedItem[];
  docs: Record<string, DefinitionDocs>;
}

function splitDocs(items: SourcedItem[], kind: string, splitParamDescriptions: boolean): DocsSplit {
  const structure: SourcedItem[] = [];
  const docs: Record<string, DefinitionDocs> = {};

  for (const { item, source } of items) {
    const { description, examples, note, ...rest } = item;
    const name = item.name as string;
    const entry: DefinitionDocs = { description: description as string };

    if (examples !== undefined) {
      entry.examples = examples as string[];
    }
    if (note !== undefined) {
      entry.note = note as string;
    }

    if (splitParamDescriptions) {
      const paramDocs: Record<string, string> = {};

      rest.signatures = (rest.signatures as Json[]).map((signature) => ({
        ...signature,
        params: (signature.params as Json[]).map((param) => {
          const { description: paramDescription, ...paramRest } = param;

          if (paramDescription !== undefined) {
            const paramName = param.name as string;

            if (paramName in paramDocs && paramDocs[paramName] !== paramDescription) {
              throw new Error(
                `${kind}/${name}: param "${paramName}" has conflicting descriptions across ` +
                  'signatures — cannot split docs by param name'
              );
            }
            paramDocs[paramName] = paramDescription as string;
          }

          return paramRest;
        }),
      }));

      if (Object.keys(paramDocs).length > 0) {
        entry.params = paramDocs;
      }
    }

    docs[name] = entry;
    structure.push({ item: rest, source });
  }

  return { structure, docs };
}

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function camelIdentifier(name: string, suffix: string): string {
  const words = name.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  const camel = words
    .map((word, i) => (i === 0 ? word : word[0].toUpperCase() + word.slice(1)))
    .join('');

  return camel + suffix;
}

function tsString(value: string): string {
  return `'${value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')}'`;
}

function tsKey(key: string): string {
  return IDENTIFIER_RE.test(key) ? key : tsString(key);
}

function tsLiteral(value: unknown, indent: string): string {
  if (typeof value === 'string') {
    return tsString(value);
  }
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return '[]';
    }
    const inner = indent + '  ';
    const entries = value.map((item) => `${inner}${tsLiteral(item, inner)}`);

    return `[\n${entries.join(',\n')},\n${indent}]`;
  }
  if (typeof value === 'object' && value !== null) {
    const keys = Object.entries(value);
    if (keys.length === 0) {
      return '{}';
    }
    const inner = indent + '  ';
    const entries = keys.map(([key, val]) => `${inner}${tsKey(key)}: ${tsLiteral(val, inner)}`);

    return `{\n${entries.join(',\n')},\n${indent}}`;
  }

  return String(value);
}

/** Renders docs as a JSDoc block: description, note, then examples. */
function renderJsdoc(docs: DefinitionDocs | undefined): string {
  if (!docs) {
    return '';
  }

  const escape = (text: string) => text.replace(/\*\//g, '*\\/');
  const paragraphs: string[] = [escape(docs.description)];

  if (docs.note) {
    paragraphs.push(`Note: ${escape(docs.note)}`);
  }
  for (const example of docs.examples ?? []) {
    paragraphs.push(`@example\n${escape(example)}`);
  }

  const body = paragraphs
    .join('\n\n')
    .split('\n')
    .map((line) => (line ? ` * ${line}` : ' *'))
    .join('\n');

  return `/**\n${body}\n */\n`;
}

interface PerItemDirectory {
  dirName: string;
  typeName: string;
  items: SourcedItem[];
  /** JSDoc content per item name. */
  jsdocByName: Record<string, DefinitionDocs>;
  barrelConst: string;
}

/** Emits one module per definition (1:1 with the source JSON) plus an index barrel. */
function renderPerItemDirectory(options: PerItemDirectory): GeneratedFile[] {
  const { dirName, typeName, items, jsdocByName, barrelConst } = options;
  const files: GeneratedFile[] = [];
  const identifiers = new Map<string, string>();

  for (const { item, source } of items) {
    const name = item.name as string;
    const identifier = camelIdentifier(name, 'Definition');

    if ([...identifiers.values()].includes(identifier)) {
      throw new Error(`${dirName}: identifier collision for "${name}" (${identifier})`);
    }
    identifiers.set(name, identifier);

    files.push({
      relativePath: `${dirName}/${name}.ts`,
      content:
        `${LICENSE_HEADER}\n\n${sourcedNotice(source)}\n\n` +
        `import type { ${typeName} } from '../../definition_types';\n\n` +
        renderJsdoc(jsdocByName[name]) +
        `const definition: ${typeName} = ${tsLiteral(item, '')};\n\n` +
        `export default definition;\n`,
    });
  }

  const imports = [...identifiers.entries()]
    .map(([name, identifier]) => `import ${identifier} from './${name}';`)
    .join('\n');
  const barrelEntries = [...identifiers.values()]
    .map((identifier) => `  ${identifier},`)
    .join('\n');

  files.push({
    relativePath: `${dirName}/index.ts`,
    content:
      `${LICENSE_HEADER}\n\n${GENERATED_NOTICE}\n\n` +
      `import type { ${typeName} } from '../../definition_types';\n\n` +
      `${imports}\n\n` +
      `export const ${barrelConst}: ${typeName}[] = [\n${barrelEntries}\n];\n`,
  });

  return files;
}

/** Emits a docs module per definition plus an index barrel (a name-keyed record). */
function renderDocsDirectory(
  dirName: string,
  barrelConst: string,
  docs: Record<string, DefinitionDocs>,
  sourceByName: Record<string, string>
): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const identifiers = new Map<string, string>();

  for (const [name, entry] of Object.entries(docs)) {
    const identifier = camelIdentifier(name, 'Docs');
    identifiers.set(name, identifier);

    files.push({
      relativePath: `${dirName}/${name}.ts`,
      content:
        `${LICENSE_HEADER}\n\n${sourcedNotice(sourceByName[name])}\n\n` +
        `import type { DefinitionDocs } from '../../definition_types';\n\n` +
        `const docs: DefinitionDocs = ${tsLiteral(entry, '')};\n\n` +
        `export default docs;\n`,
    });
  }

  const imports = [...identifiers.entries()]
    .map(([name, identifier]) => `import ${identifier} from './${name}';`)
    .join('\n');
  const barrelEntries = [...identifiers.entries()]
    .map(([name, identifier]) => `  ${tsKey(name)}: ${identifier},`)
    .join('\n');

  files.push({
    relativePath: `${dirName}/index.ts`,
    content:
      `${LICENSE_HEADER}\n\n${GENERATED_NOTICE}\n\n` +
      `import type { DefinitionDocs } from '../../definition_types';\n\n` +
      `${imports}\n\n` +
      `export const ${barrelConst}: Record<string, DefinitionDocs> = {\n${barrelEntries}\n};\n`,
  });

  return files;
}

/** Emits a single aggregate module (small datasets: commands, settings, casts). */
function renderSingleModule(typeImport: string, declaration: string, value: unknown): string {
  return (
    `${LICENSE_HEADER}\n\n${GENERATED_NOTICE}\n\n` +
    `import type { ${typeImport} } from '../definition_types';\n\n` +
    `export const ${declaration} = ${tsLiteral(value, '')};\n`
  );
}

export function generateAll(elasticsearchDir: string): GenerateResult {
  const warnings: string[] = [];
  const esqlDir = join(elasticsearchDir, 'esql');
  const promqlDir = join(elasticsearchDir, 'promql');

  if (!existsSync(esqlDir)) {
    throw new Error(`No ES|QL definitions found at: ${esqlDir}`);
  }
  if (!existsSync(promqlDir)) {
    warnings.push('no promql/ directory found — emitting empty PromQL modules');
  }

  const commandItems = readDefinitions(esqlDir, 'commands', COMMAND_SPEC, warnings);
  const functionsSplit = splitDocs(
    readDefinitions(esqlDir, 'functions', FUNCTION_SPEC, warnings),
    'functions',
    true
  );
  const operatorsSplit = splitDocs(
    readDefinitions(esqlDir, 'operators', OPERATOR_SPEC, warnings),
    'operators',
    true
  );
  const settingItems = readDefinitions(esqlDir, 'settings', SETTING_SPEC, warnings);
  const inlineCasts = readInlineCastMap(esqlDir);
  const promqlFunctionsSplit = splitDocs(
    readDefinitions(promqlDir, 'functions', PROMQL_FUNCTION_SPEC, warnings),
    'promql functions',
    false
  );
  const promqlOperatorsSplit = splitDocs(
    readDefinitions(promqlDir, 'operators', PROMQL_OPERATOR_SPEC, warnings),
    'promql operators',
    false
  );

  const sourceByName = (items: SourcedItem[]): Record<string, string> =>
    Object.fromEntries(items.map(({ item, source }) => [item.name as string, source]));

  const commands = commandItems.map(({ item }) => item) as unknown as CommandDefinition[];
  const functions = functionsSplit.structure.map(
    ({ item }) => item
  ) as unknown as FunctionDefinition[];
  const operators = operatorsSplit.structure.map(
    ({ item }) => item
  ) as unknown as OperatorDefinition[];
  const settings = settingItems.map(({ item }) => item) as unknown as SettingDefinition[];
  const promqlFunctions = promqlFunctionsSplit.structure.map(
    ({ item }) => item
  ) as unknown as PromqlFunctionDefinition[];
  const promqlOperators = promqlOperatorsSplit.structure.map(
    ({ item }) => item
  ) as unknown as PromqlOperatorDefinition[];

  const files: GeneratedFile[] = [
    {
      relativePath: 'commands.ts',
      content: renderSingleModule(
        'CommandDefinition',
        'commandDefinitions: CommandDefinition[]',
        commands
      ),
    },
    {
      relativePath: 'settings.ts',
      content: renderSingleModule(
        'SettingDefinition',
        'settingDefinitions: SettingDefinition[]',
        settings
      ),
    },
    {
      relativePath: 'inline_cast.ts',
      content: renderSingleModule('InlineCastMap', 'inlineCasts: InlineCastMap', inlineCasts),
    },
    ...renderPerItemDirectory({
      dirName: 'functions',
      typeName: 'FunctionDefinition',
      items: functionsSplit.structure,
      jsdocByName: functionsSplit.docs,
      barrelConst: 'functionDefinitions',
    }),
    ...renderPerItemDirectory({
      dirName: 'operators',
      typeName: 'OperatorDefinition',
      items: operatorsSplit.structure,
      jsdocByName: operatorsSplit.docs,
      barrelConst: 'operatorDefinitions',
    }),
    ...renderPerItemDirectory({
      dirName: 'promql_functions',
      typeName: 'PromqlFunctionDefinition',
      items: promqlFunctionsSplit.structure,
      jsdocByName: promqlFunctionsSplit.docs,
      barrelConst: 'promqlFunctionDefinitions',
    }),
    ...renderPerItemDirectory({
      dirName: 'promql_operators',
      typeName: 'PromqlOperatorDefinition',
      items: promqlOperatorsSplit.structure,
      jsdocByName: promqlOperatorsSplit.docs,
      barrelConst: 'promqlOperatorDefinitions',
    }),
    ...renderDocsDirectory(
      'function_docs',
      'functionDocs',
      functionsSplit.docs,
      sourceByName(functionsSplit.structure)
    ),
    ...renderDocsDirectory(
      'operator_docs',
      'operatorDocs',
      operatorsSplit.docs,
      sourceByName(operatorsSplit.structure)
    ),
    ...renderDocsDirectory(
      'promql_function_docs',
      'promqlFunctionDocs',
      promqlFunctionsSplit.docs,
      sourceByName(promqlFunctionsSplit.structure)
    ),
    ...renderDocsDirectory(
      'promql_operator_docs',
      'promqlOperatorDocs',
      promqlOperatorsSplit.docs,
      sourceByName(promqlOperatorsSplit.structure)
    ),
  ];

  return {
    files,
    warnings,
    data: {
      commands,
      functions,
      functionDocs: functionsSplit.docs,
      operators,
      operatorDocs: operatorsSplit.docs,
      settings,
      inlineCasts,
      promqlFunctions,
      promqlFunctionDocs: promqlFunctionsSplit.docs,
      promqlOperators,
      promqlOperatorDocs: promqlOperatorsSplit.docs,
    },
  };
}
