/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

export const commandsNames = [
  'CHANGE_POINT',
  'COMPLETION',
  'DEDUP',
  'DISSECT',
  'DROP',
  'ENRICH',
  'EVAL',
  'EXPLAIN',
  'FORK',
  'FROM',
  'FULL JOIN',
  'FUSE',
  'GROK',
  'HIGHLIGHT',
  'INLINESTATS',
  'INSIST',
  'JOIN',
  'KEEP',
  'LEFT JOIN',
  'LIMIT',
  'LOOKUP',
  'LOOKUP JOIN',
  'METRICS_INFO',
  'METRICS',
  'MMR',
  'MV_EXPAND',
  'OPTIONS',
  'PROMQL',
  'REGISTERED_DOMAIN',
  'RENAME',
  'RERANK',
  'RIGHT JOIN',
  'ROW',
  'SAMPLE',
  'SET',
  'SHOW',
  'SORT',
  'STATS',
  'TIMESERIES',
  'TS',
  'TS_COLLAPSE',
  'TS_INFO',
  'URI_PARTS',
  'USER_AGENT',
  'WHERE',
];
