/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/**
 * TypeScript shapes of the ES|QL and PromQL language definition JSON
 * generated by the Elasticsearch docs tooling and synced into
 * `elasticsearch/` by the grammar sync CI job.
 */

/** A single item from `elasticsearch/esql/<project>/definition/commands/`. */
export interface CommandDefinition {
  name: string;
  /** License tier required for the command, e.g. `'PLATINUM'`. */
  license?: string;
  observabilityTier?: string;
}

export interface ParamHint {
  kind: string;
  entityType?: string;
  allowedValues?: string[];
  constraints?: Record<string, string>;
}

export interface SignatureParam {
  name: string;
  type: string;
  optional: boolean;
  /**
   * Present only in PromQL definitions, where it varies per signature. For
   * ES|QL definitions it is identical across all signatures of a definition
   * and lives in the docs modules instead.
   */
  description?: string;
  hint?: ParamHint;
  /** Named map-parameter descriptors in the upstream pseudo-format, kept verbatim. */
  mapParams?: string;
}

export interface Signature {
  params: SignatureParam[];
  variadic: boolean;
  returnType: string;
  /** License tier required for this specific signature, e.g. `'PLATINUM'`. */
  license?: string;
}

export interface DefinitionDocs {
  description: string;
  examples?: string[];
  note?: string;
  /**
   * ES|QL only: parameter descriptions by parameter name.
   */
  params?: Record<string, string>;
}

/** A single item from `elasticsearch/esql/<project>/definition/functions/`. */
export interface FunctionDefinition {
  /** Function kind: 'scalar' | 'agg' | 'grouping' | etc. */
  type: string;
  name: string;
  signatures: Signature[];
  preview: boolean;
  snapshotOnly: boolean;
  license?: string;
  observabilityTier?: string;
  tsdbCompatible?: boolean;
}

/** A single item from `elasticsearch/esql/<project>/definition/operators/`. */
export interface OperatorDefinition {
  /** The operator symbol as written in queries, e.g. `'+'`, `'::'`, `'IN'`. */
  operator: string;
  name: string;
  titleName?: string;
  signatures: Signature[];
  preview: boolean;
  snapshotOnly: boolean;
}

/** A single item from `elasticsearch/esql/<project>/definition/settings/` — a `SET` command setting. */
export interface SettingDefinition {
  name: string;
  /** Accepted value types, e.g. `['boolean', 'map_param']`. */
  type: string[];
  description: string;
  serverlessOnly: boolean;
  preview: boolean;
  snapshotOnly: boolean;
  /** Named map-parameter descriptors in the upstream pseudo-format, kept verbatim. */
  mapParams?: string;
}

export type InlineCastMap = Record<string, string>;

/** A single item from `elasticsearch/promql/<project>/definition/functions/`. */
export interface PromqlFunctionDefinition {
  /** Function kind: 'value_transformation' | 'within_series' | ... */
  type: string;
  name: string;
  signatures: Signature[];
  snapshotOnly: boolean;
}

/** A single item from `elasticsearch/promql/<project>/definition/operators/`. */
export interface PromqlOperatorDefinition {
  /** Operator kind: 'operator' | 'label_matching_operator' | ... */
  type: string;
  /** The operator symbol as written in queries, e.g. `'+'`, `'=~'`. */
  operator: string;
  name: string;
  signatures: Signature[];
  snapshotOnly: boolean;
}
